export type Zone = "floor" | "desk" | "wall-left" | "wall-right";
export type Category =
  | "desk"
  | "monitor"
  | "chair"
  | "mouse"
  | "keyboard"
  | "computer"
  | "headphones"
  | "accessories"
  | "plant"
  | "floor"
  | "wall";

export interface DeskSurface {
  widthM: number;
  depthM: number;
  offsetXM: number;
  offsetYM: number;
}

export interface Product {
  id: string;
  name: string;
  category: Category;
  variation: string;
  zone: Zone;
  widthM: number;
  depthM: number;
  heightM: number;
  weeklyPrice: number;
  sprite: string;
  displayWidth: number;
  displayHeight: number;
  anchorX: number;
  anchorY: number;
  footprintAnchorXM?: number;
  footprintAnchorYM?: number;
  footprintWidthM?: number;
  footprintDepthM?: number;
  rotateFootprint?: boolean;
  surfaceColor?: string;
  surfaceTexture?: string;
  deskSurface?: DeskSurface;
  fixed?: boolean;
}

const product = (value: Product) => value;

export const PRODUCTS: Product[] = [
  product({
    id: "floor-oak",
    name: "Oak Floor",
    category: "floor",
    variation: "Oak",
    zone: "floor",
    widthM: 5,
    depthM: 4,
    heightM: 0,
    weeklyPrice: 0,
    sprite: "/textures/floor-oak.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 40,
    anchorY: 40,
    surfaceTexture: "/textures/floor-oak.png",
    fixed: true,
  }),
  product({
    id: "floor-walnut",
    name: "Walnut Floor",
    category: "floor",
    variation: "Walnut",
    zone: "floor",
    widthM: 5,
    depthM: 4,
    heightM: 0,
    weeklyPrice: 0,
    sprite: "/textures/floor-walnut.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 40,
    anchorY: 40,
    surfaceTexture: "/textures/floor-walnut.png",
    fixed: true,
  }),
  product({
    id: "floor-ash",
    name: "Ash Floor",
    category: "floor",
    variation: "Ash",
    zone: "floor",
    widthM: 5,
    depthM: 4,
    heightM: 0,
    weeklyPrice: 0,
    sprite: "/textures/floor-ash.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 40,
    anchorY: 40,
    surfaceTexture: "/textures/floor-ash.png",
    fixed: true,
  }),
  product({
    id: "floor-concrete",
    name: "Concrete Floor",
    category: "floor",
    variation: "Concrete",
    zone: "floor",
    widthM: 5,
    depthM: 4,
    heightM: 0,
    weeklyPrice: 0,
    sprite: "/textures/concrete.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 40,
    anchorY: 40,
    surfaceTexture: "/textures/concrete.png",
    fixed: true,
  }),
  ...[
    ["wall-white", "White Wall", "White", "#e8e5de"],
    ["wall-greige", "Greige Wall", "Greige", "#b8b0a3"],
    ["wall-charcoal", "Charcoal Wall", "Charcoal", "#31322e"],
  ].map(([id, name, variation, surfaceColor]) =>
    product({
      id,
      name,
      category: "wall",
      variation,
      zone: "wall-left",
      widthM: 5,
      depthM: 0,
      heightM: 2.7,
      weeklyPrice: 0,
      sprite: "/textures/concrete.png",
      displayWidth: 80,
      displayHeight: 80,
      anchorX: 40,
      anchorY: 40,
      surfaceColor,
      fixed: true,
    }),
  ),
  product({
    id: "wall-concrete",
    name: "Concrete Wall",
    category: "wall",
    variation: "Concrete",
    zone: "wall-left",
    widthM: 5,
    depthM: 0,
    heightM: 2.7,
    weeklyPrice: 0,
    sprite: "/textures/concrete.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 40,
    anchorY: 40,
    surfaceTexture: "/textures/concrete.png",
    fixed: true,
  }),
  product({
    id: "desk-graphite",
    name: "Graphite Studio Desk",
    category: "desk",
    variation: "Graphite",
    zone: "floor",
    widthM: 2.35,
    depthM: 1,
    heightM: 0.75,
    weeklyPrice: 18,
    sprite: "/sprites/desk-graphite.png",
    displayWidth: 330,
    displayHeight: 245,
    anchorX: 211,
    anchorY: 147,
    footprintAnchorXM: 0.49,
    footprintAnchorYM: 0.53,
    rotateFootprint: true,
    deskSurface: { widthM: 1.14, depthM: 2.5, offsetXM: 0.25, offsetYM: 0.16 },
    fixed: true,
  }),
  product({
    id: "desk-oak",
    name: "Warm Oak Studio Desk",
    category: "desk",
    variation: "Oak",
    zone: "floor",
    widthM: 2.35,
    depthM: 1,
    heightM: 0.75,
    weeklyPrice: 21,
    sprite: "/sprites/desk-oak.png",
    displayWidth: 330,
    displayHeight: 245,
    anchorX: 211,
    anchorY: 147,
    footprintAnchorXM: 0.49,
    footprintAnchorYM: 0.53,
    footprintWidthM: 2,
    footprintDepthM: 1,
    rotateFootprint: true,
    deskSurface: { widthM: 1.14, depthM: 2.5, offsetXM: 0.25, offsetYM: 0.16 },
    fixed: true,
  }),
  product({
    id: "monitor-black",
    name: "27-inch Monitor",
    category: "monitor",
    variation: "Black",
    zone: "desk",
    widthM: 0.62,
    depthM: 0.22,
    heightM: 0.48,
    weeklyPrice: 9,
    sprite: "/sprites/monitor-black.png?v=2",
    displayWidth: 126,
    displayHeight: 116,
    anchorX: 63,
    anchorY: 108,
    rotateFootprint: true,
  }),
  product({
    id: "monitor-white",
    name: "27-inch Monitor",
    category: "monitor",
    variation: "White",
    zone: "desk",
    widthM: 0.62,
    depthM: 0.22,
    heightM: 0.48,
    weeklyPrice: 10,
    sprite: "/sprites/monitor-white.png",
    displayWidth: 126,
    displayHeight: 116,
    anchorX: 63,
    anchorY: 108,
    footprintWidthM: 0.62,
    footprintDepthM: 0.22,
    footprintAnchorXM: 0.16,
    footprintAnchorYM: 0.25,
    rotateFootprint: true,
  }),
  product({
    id: "monitor-dell-24",
    name: '24" Dell UltraSharp U2424H',
    category: "monitor",
    variation: "Black",
    zone: "desk",
    widthM: 0.54,
    depthM: 0.18,
    heightM: 0.36,
    weeklyPrice: 8,
    sprite: "/sprites/monitor-dell-24.png",
    displayWidth: 110,
    displayHeight: 140,
    anchorX: 86,
    anchorY: 142,
    footprintWidthM: 0.5,
    footprintDepthM: 0.18,
    footprintAnchorXM: 0.73,
    footprintAnchorYM: 0.41,
    rotateFootprint: true,
  }),
  product({
    id: "monitor-apple-27",
    name: '27" Apple Studio Display XDR',
    category: "monitor",
    variation: "Silver",
    zone: "desk",
    widthM: 0.62,
    depthM: 0.4,
    heightM: 0.48,
    weeklyPrice: 14,
    sprite: "/sprites/monitor-apple-27.png",
    displayWidth: 120,
    displayHeight: 180,
    anchorX: 88,
    anchorY: 120,
    footprintWidthM: 0.76,
    footprintDepthM: 0.4,
    footprintAnchorXM: 0.14,
    footprintAnchorYM: -0.05,
    rotateFootprint: true,
  }),
  product({
    id: "monitor-lg-45",
    name: '45" LG UltraGear 45GX950A',
    category: "monitor",
    variation: "Black",
    zone: "desk",
    widthM: 1.08,
    depthM: 0.3,
    heightM: 0.46,
    weeklyPrice: 18,
    sprite: "/sprites/monitor-lg-45.png",
    displayWidth: 120,
    displayHeight: 160,
    anchorX: 64,
    anchorY: 120,
    rotateFootprint: true,
  }),
  product({
    id: "chair-mesh",
    name: "Mesh Task Chair",
    category: "chair",
    variation: "Mesh",
    zone: "floor",
    widthM: 0.7,
    depthM: 0.7,
    heightM: 1.15,
    weeklyPrice: 12,
    sprite: "/sprites/chair-mesh.png",
    displayWidth: 170,
    displayHeight: 205,
    anchorX: 85,
    anchorY: 160,
  }),
  product({
    id: "chair-soft",
    name: "Soft Task Chair",
    category: "chair",
    variation: "Soft",
    zone: "floor",
    widthM: 0.7,
    depthM: 0.7,
    heightM: 1.1,
    weeklyPrice: 14,
    sprite: "/sprites/chair-soft.png",
    displayWidth: 170,
    displayHeight: 198,
    anchorX: 85,
    anchorY: 182,
  }),
  product({
    id: "chair-black",
    name: "High-Back Mesh Chair",
    category: "chair",
    variation: "Black",
    zone: "floor",
    widthM: 0.7,
    depthM: 0.7,
    heightM: 1.25,
    weeklyPrice: 15,
    sprite: "/sprites/chair-black.png",
    displayWidth: 170,
    displayHeight: 205,
    anchorX: 85,
    anchorY: 190,
  }),
  product({
    id: "chair-maroon",
    name: "Maroon Task Chair",
    category: "chair",
    variation: "Maroon",
    zone: "floor",
    widthM: 0.7,
    depthM: 0.7,
    heightM: 1.2,
    weeklyPrice: 14,
    sprite: "/sprites/chair-maroon.png",
    displayWidth: 170,
    displayHeight: 205,
    anchorX: 80,
    anchorY: 160,
    footprintWidthM: 0.7,
    footprintDepthM: 0.7,
    footprintAnchorXM: -0.05,
    footprintAnchorYM: 0.14,
  }),
  product({
    id: "mouse-black",
    name: "Wireless Mouse",
    category: "mouse",
    variation: "Black",
    zone: "desk",
    widthM: 0.07,
    depthM: 0.12,
    heightM: 0.04,
    weeklyPrice: 2,
    sprite: "/sprites/mouse-black.png?v=2",
    displayWidth: 28,
    displayHeight: 19,
    anchorX: 19,
    anchorY: 22,
    footprintWidthM: 0.07,
    footprintDepthM: 0.12,
    footprintAnchorXM: 0.1,
    footprintAnchorYM: 0.1,
    rotateFootprint: true,
  }),
  product({
    id: "mouse-sand",
    name: "Wireless Mouse",
    category: "mouse",
    variation: "Sand",
    zone: "desk",
    widthM: 0.07,
    depthM: 0.12,
    heightM: 0.04,
    weeklyPrice: 2,
    sprite: "/sprites/mouse-sand.png",
    displayWidth: 28,
    displayHeight: 19,
    anchorX: 19,
    anchorY: 22,
    rotateFootprint: true,
  }),
  product({
    id: "mouse-white",
    name: "Wireless Mouse",
    category: "mouse",
    variation: "White",
    zone: "desk",
    widthM: 0.07,
    depthM: 0.12,
    heightM: 0.04,
    weeklyPrice: 2,
    sprite: "/sprites/mouse-white.png",
    displayWidth: 28,
    displayHeight: 19,
    anchorX: 19,
    anchorY: 22,
    footprintWidthM: 0.07,
    footprintDepthM: 0.12,
    footprintAnchorXM: 0.14,
    footprintAnchorYM: 0.14,
    rotateFootprint: true,
  }),
  product({
    id: "keyboard-black",
    name: "Compact Keyboard",
    category: "keyboard",
    variation: "Black",
    zone: "desk",
    widthM: 0.44,
    depthM: 0.14,
    heightM: 0.03,
    weeklyPrice: 3,
    sprite: "/sprites/keyboard-black.png?v=2",
    displayWidth: 88,
    displayHeight: 48,
    anchorX: 44,
    anchorY: 38,
    footprintWidthM: 0.44,
    footprintDepthM: 0.14,
    footprintAnchorXM: 0.13,
    footprintAnchorYM: 0.2,
    rotateFootprint: true,
  }),
  product({
    id: "keyboard-white",
    name: "Compact Keyboard",
    category: "keyboard",
    variation: "White",
    zone: "desk",
    widthM: 0.44,
    depthM: 0.14,
    heightM: 0.03,
    weeklyPrice: 3,
    sprite: "/sprites/keyboard-white.png",
    displayWidth: 88,
    displayHeight: 48,
    anchorX: 44,
    anchorY: 38,
    footprintWidthM: 0.44,
    footprintDepthM: 0.14,
    footprintAnchorXM: 0.12,
    footprintAnchorYM: 0.24,
    rotateFootprint: true,
  }),
  product({
    id: "keyboard-apple-magic",
    name: "Apple Magic Keyboard",
    category: "keyboard",
    variation: "White",
    zone: "desk",
    widthM: 0.42,
    depthM: 0.12,
    heightM: 0.02,
    weeklyPrice: 4,
    sprite: "/sprites/apple-magic-keyboard.png",
    displayWidth: 70,
    displayHeight: 60,
    anchorX: 60,
    anchorY: 36,
    footprintWidthM: 0.42,
    footprintDepthM: 0.12,
    footprintAnchorXM: 0.22,
    footprintAnchorYM: 0.07,
    rotateFootprint: true,
  }),
  product({
    id: "keyboard-wobkey-rainy-75",
    name: "WOBKEY Rainy 75",
    category: "keyboard",
    variation: "White",
    zone: "desk",
    widthM: 0.36,
    depthM: 0.14,
    heightM: 0.03,
    weeklyPrice: 4,
    sprite: "/sprites/wobkey-rainy-75.png",
    displayWidth: 100,
    displayHeight: 70,
    anchorX: 60,
    anchorY: 68,
    footprintWidthM: 0.36,
    footprintDepthM: 0.14,
    footprintAnchorXM: 0.43,
    footprintAnchorYM: 0.42,
    rotateFootprint: true,
  }),
  product({
    id: "computer-mac-mini-m4",
    name: "Mac mini M4",
    category: "computer",
    variation: "Silver",
    zone: "desk",
    widthM: 0.2,
    depthM: 0.2,
    heightM: 0.05,
    weeklyPrice: 12,
    sprite: "/sprites/mac-mini-m4.png",
    displayWidth: 40,
    displayHeight: 40,
    anchorX: 45,
    anchorY: 66,
    footprintWidthM: 0.2,
    footprintDepthM: 0.2,
    footprintAnchorXM: 0.69,
    footprintAnchorYM: 0.43,
  }),
  product({
    id: "apple-airpods-max",
    name: "Apple AirPods Max",
    category: "accessories",
    variation: "Silver",
    zone: "desk",
    widthM: 0.28,
    depthM: 0.22,
    heightM: 0.26,
    weeklyPrice: 8,
    sprite: "/sprites/apple-airpods-max.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 61,
    anchorY: 104,
    footprintAnchorXM: 0.63,
    footprintAnchorYM: 0.39,
    rotateFootprint: true,
  }),
  product({
    id: "desk-lamp",
    name: "Desk Lamp",
    category: "accessories",
    variation: "White",
    zone: "desk",
    widthM: 0.2,
    depthM: 0.2,
    heightM: 0.48,
    weeklyPrice: 3,
    sprite: "/sprites/desk-lamp.png",
    displayWidth: 90,
    displayHeight: 90,
    anchorX: 42,
    anchorY: 106,
    footprintAnchorXM: 0.44,
    footprintAnchorYM: 0.34,
    rotateFootprint: true,
  }),
  product({
    id: "mini-speaker",
    name: "Mini Speaker",
    category: "accessories",
    variation: "White",
    zone: "desk",
    widthM: 0.24,
    depthM: 0.24,
    heightM: 0.2,
    weeklyPrice: 4,
    sprite: "/sprites/mini-speaker.png",
    displayWidth: 65,
    displayHeight: 65,
    anchorX: 60,
    anchorY: 107,
    footprintAnchorXM: 0.88,
    footprintAnchorYM: 0.53,
    rotateFootprint: true,
  }),
  product({
    id: "desk-plant-1",
    name: "Bonsai Desk Plant",
    category: "plant",
    variation: "Bonsai",
    zone: "desk",
    widthM: 0.22,
    depthM: 0.22,
    heightM: 0.2,
    weeklyPrice: 3,
    sprite: "/sprites/desk-plant-1.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 60,
    anchorY: 98,
    footprintAnchorXM: 0.63,
    footprintAnchorYM: 0.39,
    rotateFootprint: true,
  }),
  product({
    id: "desk-plant-2",
    name: "Succulent Desk Plant",
    category: "plant",
    variation: "Succulent",
    zone: "desk",
    widthM: 0.2,
    depthM: 0.2,
    heightM: 0.18,
    weeklyPrice: 2,
    sprite: "/sprites/desk-plant-2.png",
    displayWidth: 80,
    displayHeight: 80,
    anchorX: 60,
    anchorY: 93,
    footprintAnchorXM: 0.63,
    footprintAnchorYM: 0.39,
    rotateFootprint: true,
  }),
  product({
    id: "plant-fiddle-leaf",
    name: "IKEA FEJKA Fiddle-Leaf Fig",
    category: "plant",
    variation: "Fiddle-Leaf Fig",
    zone: "floor",
    widthM: 0.45,
    depthM: 0.45,
    heightM: 1.2,
    weeklyPrice: 6,
    sprite: "/sprites/plant-fiddle-leaf.png",
    displayWidth: 180,
    displayHeight: 210,
    anchorX: 90,
    anchorY: 177,
    footprintWidthM: 0.45,
    footprintDepthM: 0.45,
    footprintAnchorXM: 0.26,
    footprintAnchorYM: 0.26,
  }),
  product({
    id: "plant-snake-new",
    name: "Snake Plant",
    category: "plant",
    variation: "Snake Plant",
    zone: "floor",
    widthM: 0.4,
    depthM: 0.4,
    heightM: 0.85,
    weeklyPrice: 5,
    sprite: "/sprites/plant-snake-new.png",
    displayWidth: 180,
    displayHeight: 210,
    anchorX: 90,
    anchorY: 183,
    footprintWidthM: 0.4,
    footprintDepthM: 0.4,
    footprintAnchorXM: 0.34,
    footprintAnchorYM: 0.35,
  }),
  product({
    id: "painting-bauhaus-black",
    name: "Bauhaus 1923 Black Painting",
    category: "accessories",
    variation: "Black",
    zone: "wall-left",
    widthM: 0.6,
    depthM: 0.04,
    heightM: 0.8,
    weeklyPrice: 4,
    sprite: "/sprites/painting-black.png",
    displayWidth: 100,
    displayHeight: 100,
    anchorX: 90,
    anchorY: 97,
    footprintWidthM: 0.5,
    footprintDepthM: 0.38,
    footprintAnchorXM: -0.49,
    footprintAnchorYM: -0.42,
  }),
  product({
    id: "painting-bauhaus-green",
    name: "Bauhaus Green Painting",
    category: "accessories",
    variation: "Green",
    zone: "wall-left",
    widthM: 0.6,
    depthM: 0.04,
    heightM: 0.8,
    weeklyPrice: 4,
    sprite: "/sprites/painting-green.png",
    displayWidth: 100,
    displayHeight: 100,
    anchorX: 90,
    anchorY: 97,
    footprintWidthM: 0.5,
    footprintDepthM: 0.38,
    footprintAnchorXM: -0.49,
    footprintAnchorYM: -0.42,
  }),
  product({
    id: "clock-navy",
    name: "Navy Wall Clock",
    category: "accessories",
    variation: "Navy",
    zone: "wall-left",
    widthM: 0.7,
    depthM: 0.05,
    heightM: 0.4,
    weeklyPrice: 3,
    sprite: "/sprites/clock.png",
    displayWidth: 90,
    displayHeight: 90,
    anchorX: 45,
    anchorY: 47,
  }),
  product({
    id: "headphones-blue",
    name: "Studio Headphones",
    category: "headphones",
    variation: "Blue",
    zone: "desk",
    widthM: 0.2,
    depthM: 0.2,
    heightM: 0.32,
    weeklyPrice: 4,
    sprite: "/sprites/headphones-blue.png",
    displayWidth: 70,
    displayHeight: 78,
    anchorX: 35,
    anchorY: 71,
  }),
  product({
    id: "headphones-black",
    name: "Studio Headphones",
    category: "headphones",
    variation: "Black",
    zone: "desk",
    widthM: 0.2,
    depthM: 0.2,
    heightM: 0.32,
    weeklyPrice: 4,
    sprite: "/sprites/headphones-black.png",
    displayWidth: 70,
    displayHeight: 78,
    anchorX: 35,
    anchorY: 71,
  }),
  product({
    id: "plant-snake",
    name: "Snake Plant",
    category: "plant",
    variation: "Snake",
    zone: "floor",
    widthM: 0.45,
    depthM: 0.45,
    heightM: 1.1,
    weeklyPrice: 5,
    sprite: "/sprites/plant-snake.png",
    displayWidth: 116,
    displayHeight: 196,
    anchorX: 58,
    anchorY: 184,
  }),
  product({
    id: "plant-palm",
    name: "Parlor Palm",
    category: "plant",
    variation: "Palm",
    zone: "floor",
    widthM: 0.5,
    depthM: 0.5,
    heightM: 1.2,
    weeklyPrice: 6,
    sprite: "/sprites/plant-palm.png",
    displayWidth: 130,
    displayHeight: 210,
    anchorX: 65,
    anchorY: 196,
  }),
];

export const PRODUCTS_BY_ID = Object.fromEntries(PRODUCTS.map((item) => [item.id, item])) as Record<
  string,
  Product
>;
